controller_list:
  - name: fake_platform_lift_manipulator_controller
    joints:
      - platform_joint_1
      - platform_joint_2
      - platform_joint_3
      - rail_actuation_joint
      - robot_joint_1
      - robot_joint_2
      - robot_joint_3
      - robot_joint_4
      - robot_joint_5
      - robot_joint_6
  - name: fake_lift_manipulator_controller
    joints:
      - rail_actuation_joint
      - robot_joint_1
      - robot_joint_2
      - robot_joint_3
      - robot_joint_4
      - robot_joint_5
      - robot_joint_6
  - name: fake_manipulator_controller
    joints:
      - robot_joint_1
      - robot_joint_2
      - robot_joint_3
      - robot_joint_4
      - robot_joint_5
      - robot_joint_6
  - name: fake_platform_controller
    joints:
      - platform_joint_1
      - platform_joint_2
      - platform_joint_3
  - name: fake_lift_manipulator_camera_controller
    joints:
      - rail_actuation_joint
      - robot_joint_1
      - robot_joint_2
      - robot_joint_3
      - robot_joint_4
      - robot_joint_5
      - robot_joint_6