# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  platform_joint_1:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  platform_joint_2:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  platform_joint_3:
    has_velocity_limits: true
    max_velocity: 0.15
    has_acceleration_limits: false
    max_acceleration: 0
  rail_actuation_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  robot_joint_1:
    has_velocity_limits: true
    max_velocity: 1.57079632679
    has_acceleration_limits: false
    max_acceleration: 0
  robot_joint_2:
    has_velocity_limits: true
    max_velocity: 1.4835298642
    has_acceleration_limits: false
    max_acceleration: 0
  robot_joint_3:
    has_velocity_limits: true
    max_velocity: 1.4835298642
    has_acceleration_limits: false
    max_acceleration: 0
  robot_joint_4:
    has_velocity_limits: true
    max_velocity: 3.05432619099
    has_acceleration_limits: false
    max_acceleration: 0
  robot_joint_5:
    has_velocity_limits: true
    max_velocity: 2.53072741539
    has_acceleration_limits: false
    max_acceleration: 0
  robot_joint_6:
    has_velocity_limits: true
    max_velocity: 4.18879020479
    has_acceleration_limits: false
    max_acceleration: 0